version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/
    ports:
      - '8000:8000'
  frontend:
    stdin_open: true
    build: ./frontend
    volumes:
      - ./frontend:/app/
    ports:
      - '3000:3000'
